<?php

class ilCourseWizardGlobalScreenModificationProvider extends \ILIAS\GlobalScreen\Scope\Layout\Provider\AbstractModificationPluginProvider
{

    public function isInterestedInContexts() : \ILIAS\GlobalScreen\ScreenContext\Stack\ContextCollection
    {
        return $this->context_collection->repository();
    }

    private function isContentViewPage(\Psr\Http\Message\RequestInterface $request)
    {
        $full_script_name = isset($request->getServerParams()['SCRIPT_NAME']) ? explode('/', $request->getServerParams()['SCRIPT_NAME']) : array('');
        $script_name = $full_script_name[count($full_script_name)-1];

        // Check for request on ilias.php
        if($script_name == 'ilias.php' && isset($request->getQueryParams()['cmd'])) {
            return $request->getQueryParams()['cmd'] == 'view' || $request->getQueryParams()['cmd'] == 'render';
        }

        // Check for request on goto.php
        if($script_name == 'goto.php') {
            return true;
        }
    }

    public function getContentModification(\ILIAS\GlobalScreen\ScreenContext\Stack\CalledContexts $screen_context_stack) : ?\ILIAS\GlobalScreen\Scope\Layout\Factory\ContentModification
    {
        // TODO: Needs refactoring
        if($screen_context_stack->current()->hasReferenceId()){

            $ref_id = $screen_context_stack->current()->getReferenceId()->toInt();
            $request = $this->dic->http()->request();
            if(ilObject::_lookupType($ref_id, true) == 'crs'
                && count($this->dic->repositoryTree()->getChilds($ref_id)) <= 0
                && ilObject::_lookupType($this->dic->repositoryTree()->getParentId($ref_id), true) == 'cat'
                && $this->isContentViewPage($this->dic->http()->request())) {

                $tpl = $this->dic->ui()->mainTemplate();
                $tpl->addJavaScript($this->plugin->getDirectory() . '/js/modal_functions.js');
                $tpl->addCss($this->plugin->getDirectory() . '/templates/default/xcwi_modal_styles.css');

                $ctrl = $this->dic->ctrl();
                $ctrl->setParameterByClass(ilCourseWizardApiGUI::class, 'ref_id', $ref_id);
                $link = $ctrl->getLinkTargetByClass(ilCourseWizardApiGUI::API_CTRL_PATH, ilCourseWizardApiGUI::CMD_ASYNC_BASE_MODAL, '', true);
                $tpl->addOnLoadCode('$.get("'.$link.'", function(data){$("body").append(data);})');
            }
        }
        return parent::getContentModification($screen_context_stack); // TODO: Change the autogenerated stub
    }

}