<?php declare(strict_types = 1);

class ilCourseWizardPlugin extends ilRepositoryObjectPlugin
{
    public const ID = 'xcwi';
    public const LANG_PREFIX = 'rep_robj_xcwi_';

    /** @var \CourseWizard\DB\PluginConfigKeyValueStore  */
    private $plugin_config_repo;
    private $role_folder_id;

    public function __construct()
    {
        parent::__construct();

        global $DIC;
        if ($DIC->isDependencyAvailable('globalScreen')) {
            $this->provider_collection->setModificationProvider(new ilCourseWizardGlobalScreenModificationProvider($DIC, $this));
        }

        $this->plugin_config_repo = new \CourseWizard\DB\PluginConfigKeyValueStore($this->db);
        $this->role_folder_id = ROLE_FOLDER_ID;
    }

    private function removeDefinedRoleTemplates(array $rolt_definition_list)
    {
        global $DIC;

        /** @var \CourseWizard\role\RoleTemplatesDefinition $rolt_definition */
        foreach ($rolt_definition_list as $rolt_definition) {
            $obj_id = $this->plugin_config_repo->get($rolt_definition->getConfKey());

            if ($obj_id != null) {
                $rolt = ilObjectFactory::getInstanceByObjId($obj_id, false);

                if ($rolt != null) {
                    $rolt->delete();
                }
            }
        }
    }

    public function getPluginName()
    {
        return 'CourseWizard';
    }

    public function activate()
    {
        if ($this->plugin_config_repo->get(\CourseWizard\DB\PluginConfigKeyValueStore::KEY_PLUGIN_ARRANGED) != '1') {
            $this->arrangePluginArtifacts();
            $this->plugin_config_repo->set(\CourseWizard\DB\PluginConfigKeyValueStore::KEY_PLUGIN_ARRANGED, '1');

            ilUtil::sendSuccess($this->txt('plugin_db_artifacts_created'), true);
        }

        return parent::activate(); // TODO: Change the autogenerated stub
    }

    protected function uninstallCustom()
    {
        $this->removeDefinedRoleTemplates(\CourseWizard\role\RoleTemplatesDefinition::getRoleTemplateDefinitions());

        $dbs = array(\CourseWizard\DB\CourseTemplateRepository::TABLE_NAME,
                     \CourseWizard\DB\PluginConfigKeyValueStore::TABLE_NAME,
                     \CourseWizard\DB\TemplateContainerConfigurationRepository::TABLE_NAME,
                     \CourseWizard\DB\WizardFlowRepository::TABLE_NAME
            );

        foreach ($dbs as $db) {
            $this->db->dropTable($db, false);
        }
    }

    private function arrangePluginArtifacts()
    {
        /** @var \CourseWizard\role\RoleTemplatesDefinition $rolt_definition */
        foreach (\CourseWizard\role\RoleTemplatesDefinition::getRoleTemplateDefinitions() as $rolt_definition) {
            $obj_role_template = $this->createRoleTemplate($rolt_definition);

            $this->plugin_config_repo->set($rolt_definition->getConfKey(), "{$obj_role_template->getId()}");
            $this->setRoleTemplatePermissions($obj_role_template, $rolt_definition);

            ilUtil::sendSuccess($this->txt('plugin_rolt_created') . ' ' . $rolt_definition->getTitle());
        }
    }

    private function setRoleTemplatePermissions(ilObjRoleTemplate $role_template, \CourseWizard\role\RoleTemplatesDefinition $rolt_definition)
    {
        global $DIC;

        $rbac_review = $DIC->rbac()->review();

        // For each subtype ...
        $subs = ilObjRole::getSubObjects('root', false);
        foreach ($subs as $subtype => $def) {
            $operations = $rbac_review->getOperationsByTypeAndClass($subtype, 'object');

            $enabled_operations = array();
            // ... check each possible operation (for this type, e.g. 'blog' -> 'read') ...
            foreach ($operations as $ops_id) {
                $operation = $rbac_review->getOperation($ops_id);

                // ... and check, if the operation should be used for the given role template
                if ($rolt_definition->checkDefaultPermissionByOperationName($subtype, $operation['operation'])) {
                    // Collect operations in an array, since $rbac_admin->setRolePermission() only accepts an operation list
                    $enabled_operations[] = $ops_id;
                }
            }

            // If operations were selected, set those permissions for the given role template
            if (count($enabled_operations) > 0) {
                $DIC->rbac()->admin()->setRolePermission($role_template->getId(), $subtype, $enabled_operations, $this->role_folder_id);
            }
        }
    }

    private function createRoleTemplate(\CourseWizard\role\RoleTemplatesDefinition $rolt_definition) : ilObjRoleTemplate
    {
        global $DIC;
        $role_template = new ilObjRoleTemplate();
        $role_template->setTitle($rolt_definition->getTitle());
        $role_template->setDescription($rolt_definition->getDescription());
        $role_template->create();

        $rbac_admin = $DIC->rbac()->admin();
        $rbac_admin->assignRoleToFolder($role_template->getId(), $this->role_folder_id, 'n');
        $is_protected = $rolt_definition->isProtected() ? 'y' : 'n';
        $rbac_admin->setProtected($role_template->getRefId(), $role_template->getId(), $is_protected);

        return $role_template;
    }

    /**
     * @return string[]
     */
    public function getParentTypes()
    {
        $par_types = array("cat");
        return $par_types;
    }

    public function allowCopy()
    {
        return false;
    }

    public function getGlobalCrsImporterRole() : int
    {
        return (int) $this->plugin_config_repo->get(\CourseWizard\DB\PluginConfigKeyValueStore::KEY_CRS_IMPORTER_ROLE_ID);
    }

    public function langVarAsPluginLangVar(string $lang_var) : string
    {
        return self::LANG_PREFIX . $lang_var;
    }
}
